server:
  port: 20038

---
spring:
  profiles: default
  application:
    name: netplus-mall-web

---
spring:
  profiles: ygmall_test
  application:
    name: netplus-mall-web


---
spring:
  profiles: ygmall_prod
  application:
    name: netplus-mall-web



