CREATE TABLE XXL_JOB_INFO (
  ID NUMBER (11) NOT NULL,
  JOB_GROUP NUMBER(11) NOT NULL,
  JOB_DESC VARCHAR(255) NOT NULL,
  ADD_TIME DATE DEFAULT NULL,
  UPDATE_TIME DATE DEFAULT NULL,
  AUTHOR VARCHAR(64) DEFAULT NULL,
  ALARM_EMAIL VARCHAR(255) DEFAULT NULL,
  SCHEDULE_TYPE VARCHAR(50) DEFAULT 'NONE',
  SCHEDULE_CONF VARCHAR(128) DEFAULT NULL,
  MISFIRE_STRATEGY VARCHAR(50) DEFAULT 'DO_NOTHING',
  EXECUTOR_ROUTE_STRATEGY VARCHAR(50) DEFAULT NULL,
  EXECUTOR_HANDLER VARCHAR(255) DEFAULT NULL,
  EXECUTOR_PARAM VARCHAR(512) DEFAULT NULL,
  EXECUTOR_BLOCK_STRATEGY VARCHAR(50) DEFAULT NULL,
  EXECUTOR_TIMEOUT NUMBER(11) DEFAULT '0',
  EXECUTOR_FAIL_RETRY_COUNT NUMBER(11) DEFAULT '0',
  GLUE_TYPE VARCHAR(50) NOT NULL,
  GLUE_SOURCE CLOB,
  GLUE_REMARK VARCHAR(128) DEFAULT NULL,
  GLUE_UPDATETIME DATE DEFAULT NULL,
  CHILD_JOBID VARCHAR(255) DEFAULT NULL,
  TRIGGER_STATUS NUMBER(4) DEFAULT '0',
  TRIGGER_LAST_TIME NUMBER(13) DEFAULT '0',
  TRIGGER_NEXT_TIME NUMBER(13) DEFAULT '0',
  PRIMARY KEY (ID)
);

COMMENT ON COLUMN XXL_JOB_INFO.JOB_GROUP IS '执行器主键ID';
COMMENT ON COLUMN XXL_JOB_INFO.AUTHOR IS '作者';
COMMENT ON COLUMN XXL_JOB_INFO.ALARM_EMAIL IS '报警邮件';
COMMENT ON COLUMN XXL_JOB_INFO.SCHEDULE_TYPE IS '调度类型';
COMMENT ON COLUMN XXL_JOB_INFO.SCHEDULE_CONF IS '调度配置，值含义取决于调度类型';
COMMENT ON COLUMN XXL_JOB_INFO.MISFIRE_STRATEGY IS '调度过期策略';
COMMENT ON COLUMN XXL_JOB_INFO.EXECUTOR_ROUTE_STRATEGY IS '执行器路由策略';
COMMENT ON COLUMN XXL_JOB_INFO.EXECUTOR_HANDLER IS '执行器任务HANDLER';
COMMENT ON COLUMN XXL_JOB_INFO.EXECUTOR_PARAM IS '执行器任务参数';
COMMENT ON COLUMN XXL_JOB_INFO.EXECUTOR_BLOCK_STRATEGY IS '阻塞处理策略';
COMMENT ON COLUMN XXL_JOB_INFO.EXECUTOR_TIMEOUT IS '任务执行超时时间，单位秒';
COMMENT ON COLUMN XXL_JOB_INFO.EXECUTOR_FAIL_RETRY_COUNT IS '失败重试次数';
COMMENT ON COLUMN XXL_JOB_INFO.GLUE_TYPE IS 'GLUE类型';
COMMENT ON COLUMN XXL_JOB_INFO.GLUE_SOURCE IS 'GLUE源代码';
COMMENT ON COLUMN XXL_JOB_INFO.GLUE_REMARK IS 'GLUE备注';
COMMENT ON COLUMN XXL_JOB_INFO.GLUE_UPDATETIME IS 'GLUE更新时间';
COMMENT ON COLUMN XXL_JOB_INFO.CHILD_JOBID IS '子任务ID，多个逗号分隔';
COMMENT ON COLUMN XXL_JOB_INFO.TRIGGER_STATUS IS '调度状态：0-停止，1-运行';
COMMENT ON COLUMN XXL_JOB_INFO.TRIGGER_LAST_TIME IS '上次调度时间';
COMMENT ON COLUMN XXL_JOB_INFO.TRIGGER_NEXT_TIME IS '下次调度时间';

CREATE SEQUENCE XXL_JOB_INFO_ID
    MINVALUE 1
    NOMAXVALUE
    INCREMENT BY 1
    START WITH 1
NOCACHE;

CREATE OR REPLACE TRIGGER XXL_JOB_INFO_TG
BEFORE INSERT ON XXL_JOB_INFO FOR EACH ROW
BEGIN
SELECT XXL_JOB_INFO_ID.NEXTVAL INTO:NEW.ID FROM DUAL;
END;

CREATE TABLE XXL_JOB_LOG (
   ID NUMBER(20) NOT NULL,
   JOB_GROUP NUMBER(11) NOT NULL,
   JOB_ID NUMBER(11) NOT NULL,
   EXECUTOR_ADDRESS VARCHAR(255) DEFAULT NULL,
   EXECUTOR_HANDLER VARCHAR(255) DEFAULT NULL,
   EXECUTOR_PARAM VARCHAR(512) DEFAULT NULL,
   EXECUTOR_SHARDING_PARAM VARCHAR(20) DEFAULT NULL,
   EXECUTOR_FAIL_RETRY_COUNT NUMBER(11) DEFAULT '0',
   TRIGGER_TIME DATE DEFAULT NULL,
   TRIGGER_CODE NUMBER(11) NOT NULL,
   TRIGGER_MSG CLOB,
   HANDLE_TIME DATE DEFAULT NULL,
   HANDLE_CODE NUMBER(11) NOT NULL,
   HANDLE_MSG CLOB,
   ALARM_STATUS NUMBER(4) DEFAULT '0',
   PRIMARY KEY (ID)
);

create index I_trigger_time on XXL_JOB_LOG(TRIGGER_TIME);
create index I_handle_code on XXL_JOB_LOG(HANDLE_CODE);

COMMENT ON COLUMN XXL_JOB_LOG.JOB_GROUP IS '执行器主键ID';
COMMENT ON COLUMN XXL_JOB_LOG.JOB_ID IS '任务，主键ID';
COMMENT ON COLUMN XXL_JOB_LOG.EXECUTOR_ADDRESS IS '执行器地址，本次执行的地址';
COMMENT ON COLUMN XXL_JOB_LOG.EXECUTOR_HANDLER IS '执行器任务HANDLER';
COMMENT ON COLUMN XXL_JOB_LOG.EXECUTOR_PARAM IS '执行器任务参数';
COMMENT ON COLUMN XXL_JOB_LOG.EXECUTOR_SHARDING_PARAM IS '执行器任务分片参数，格式如 1/2';
COMMENT ON COLUMN XXL_JOB_LOG.EXECUTOR_FAIL_RETRY_COUNT IS '失败重试次数';
COMMENT ON COLUMN XXL_JOB_LOG.TRIGGER_TIME IS '调度-时间';
COMMENT ON COLUMN XXL_JOB_LOG.TRIGGER_CODE IS '调度-结果';
COMMENT ON COLUMN XXL_JOB_LOG.TRIGGER_MSG IS '调度-日志';
COMMENT ON COLUMN XXL_JOB_LOG.HANDLE_TIME IS '执行-时间';
COMMENT ON COLUMN XXL_JOB_LOG.HANDLE_CODE IS '执行-状态';
COMMENT ON COLUMN XXL_JOB_LOG.HANDLE_MSG IS '执行-日志';
COMMENT ON COLUMN XXL_JOB_LOG.ALARM_STATUS IS '告警状态：0-默认、1-无需告警、2-告警成功、3-告警失败';

CREATE SEQUENCE XXL_JOB_LOG_ID
    MINVALUE 1
    NOMAXVALUE
    INCREMENT BY 1
    START WITH 1
NOCACHE;

CREATE OR REPLACE TRIGGER XXL_JOB_LOG_TG
BEFORE INSERT ON XXL_JOB_LOG FOR EACH ROW
BEGIN
SELECT XXL_JOB_LOG_ID.NEXTVAL INTO:NEW.ID FROM DUAL;
END;

CREATE TABLE XXL_JOB_LOG_REPORT (
  ID NUMBER(11) NOT NULL,
  TRIGGER_DAY DATE DEFAULT NULL,
  RUNNING_COUNT NUMBER(11) DEFAULT '0',
  SUC_COUNT NUMBER(11) DEFAULT '0',
  FAIL_COUNT NUMBER(11) DEFAULT '0',
  UPDATE_TIME DATE DEFAULT NULL,
  PRIMARY KEY (ID)
);

alter table XXL_JOB_LOG_REPORT add constraint I_TRIGGER_DAY unique (TRIGGER_DAY);

COMMENT ON COLUMN XXL_JOB_LOG_REPORT.TRIGGER_DAY IS '调度-时间';
COMMENT ON COLUMN XXL_JOB_LOG_REPORT.RUNNING_COUNT IS '运行中-日志数量';
COMMENT ON COLUMN XXL_JOB_LOG_REPORT.SUC_COUNT IS '执行成功-日志数量';
COMMENT ON COLUMN XXL_JOB_LOG_REPORT.FAIL_COUNT IS '执行失败-日志数量';

CREATE SEQUENCE XXL_JOB_LOG_REPORT_ID
    MINVALUE 1
    NOMAXVALUE
    INCREMENT BY 1
    START WITH 1
NOCACHE;

CREATE OR REPLACE TRIGGER XXL_JOB_LOG_REPORT_TG
BEFORE INSERT ON XXL_JOB_LOG_REPORT FOR EACH ROW
BEGIN
SELECT XXL_JOB_LOG_REPORT_id.NEXTVAL INTO:NEW.ID FROM DUAL;
END;

CREATE TABLE XXL_JOB_LOGGLUE (
   ID NUMBER(11) NOT NULL,
   JOB_ID NUMBER(11) NOT NULL,
   GLUE_TYPE VARCHAR(50) DEFAULT NULL,
   GLUE_SOURCE CLOB,
   GLUE_REMARK VARCHAR(128) NOT NULL,
   ADD_TIME DATE DEFAULT NULL,
   UPDATE_TIME DATE DEFAULT NULL,
   PRIMARY KEY (ID)
);

COMMENT ON COLUMN XXL_JOB_LOGGLUE.JOB_ID IS '任务，主键ID';
COMMENT ON COLUMN XXL_JOB_LOGGLUE.GLUE_TYPE IS 'GLUE类型';
COMMENT ON COLUMN XXL_JOB_LOGGLUE.GLUE_SOURCE IS 'GLUE源代码';
COMMENT ON COLUMN XXL_JOB_LOGGLUE.GLUE_REMARK IS 'GLUE备注';

CREATE SEQUENCE XXL_JOB_LOGGLUE_ID
    MINVALUE 1
    NOMAXVALUE
    INCREMENT BY 1
    START WITH 1
NOCACHE;

CREATE OR REPLACE TRIGGER XXL_JOB_LOGGLUE_TG
BEFORE INSERT ON XXL_JOB_LOGGLUE FOR EACH ROW
BEGIN
SELECT XXL_JOB_LOGGLUE_ID.NEXTVAL INTO:NEW.ID FROM DUAL;
END;

CREATE TABLE XXL_JOB_REGISTRY (
    ID NUMBER(11) NOT NULL,
    REGISTRY_GROUP VARCHAR(50) NOT NULL,
    REGISTRY_KEY VARCHAR(255) NOT NULL,
    REGISTRY_VALUE VARCHAR(255) NOT NULL,
    UPDATE_TIME DATE DEFAULT NULL,
    PRIMARY KEY (ID)
);

create index I_G_K_V on XXL_JOB_REGISTRY(REGISTRY_GROUP,REGISTRY_KEY,REGISTRY_VALUE);

CREATE SEQUENCE XXL_JOB_REGISTRY_ID
    MINVALUE 1
    NOMAXVALUE
    INCREMENT BY 1
    START WITH 1
NOCACHE;

CREATE OR REPLACE TRIGGER XXL_JOB_REGISTRY_TG
BEFORE INSERT ON XXL_JOB_REGISTRY FOR EACH ROW
BEGIN
SELECT XXL_JOB_REGISTRY_ID.NEXTVAL INTO:NEW.ID FROM DUAL;
END;

CREATE TABLE XXL_JOB_GROUP (
     ID NUMBER(11) NOT NULL,
     APP_NAME VARCHAR(64) NOT NULL,
     TITLE VARCHAR(12) NOT NULL,
     ADDRESS_TYPE NUMBER(4) DEFAULT '0',
     ADDRESS_LIST CLOB,
     UPDATE_TIME DATE DEFAULT NULL,
     PRIMARY KEY (ID)
);

COMMENT ON COLUMN XXL_JOB_GROUP.APP_NAME IS '执行器APPNAME';
COMMENT ON COLUMN XXL_JOB_GROUP.TITLE IS '执行器名称';
COMMENT ON COLUMN XXL_JOB_GROUP.ADDRESS_TYPE IS '执行器地址类型：0=自动注册、1=手动录入';
COMMENT ON COLUMN XXL_JOB_GROUP.ADDRESS_LIST IS '执行器地址列表，多地址逗号分隔';

CREATE SEQUENCE XXL_JOB_GROUP_ID
    MINVALUE 1
    NOMAXVALUE
    INCREMENT BY 1
    START WITH 1
NOCACHE;

CREATE OR REPLACE TRIGGER XXL_JOB_GROUP_TG
BEFORE INSERT ON XXL_JOB_GROUP FOR EACH ROW
BEGIN
SELECT XXL_JOB_GROUP_ID.NEXTVAL INTO:NEW.ID FROM DUAL;
END;

CREATE TABLE XXL_JOB_USER (
    ID NUMBER (11) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    ROLE NUMBER(4) NOT NULL,
    PERMISSION VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (ID)
);

alter table XXL_JOB_USER add constraint I_USERNAME unique (USERNAME);

COMMENT ON COLUMN XXL_JOB_USER.USERNAME IS '账号';
COMMENT ON COLUMN XXL_JOB_USER.PASSWORD IS '密码';
COMMENT ON COLUMN XXL_JOB_USER.ROLE IS '角色：0-普通用户、1-管理员';
COMMENT ON COLUMN XXL_JOB_USER.PERMISSION IS '权限：执行器ID列表，多个逗号分割';

CREATE SEQUENCE XXL_JOB_USER_ID
    MINVALUE 1
    NOMAXVALUE
    INCREMENT BY 1
    START WITH 1
NOCACHE;

CREATE OR REPLACE TRIGGER XXL_JOB_USER_TG
BEFORE INSERT ON XXL_JOB_USER FOR EACH ROW
BEGIN
SELECT XXL_JOB_USER_ID.NEXTVAL INTO:NEW.ID FROM DUAL;
END;

CREATE TABLE XXL_JOB_LOCK (
    LOCK_NAME VARCHAR(50) NOT NULL,
    PRIMARY KEY (LOCK_NAME)
);

COMMENT ON COLUMN XXL_JOB_LOCK.LOCK_NAME IS '锁名称';

INSERT INTO XXL_JOB_GROUP(ID, APP_NAME, TITLE, ADDRESS_TYPE, ADDRESS_LIST, UPDATE_TIME) VALUES (1, 'XXL-JOB-EXECUTOR-SAMPLE', '示例执行器', 0, NULL, to_date('2018-11-03 22:21:31','yyyy-mm-dd hh24:mi:ss'));
INSERT INTO XXL_JOB_INFO(ID, JOB_GROUP, JOB_DESC, ADD_TIME, UPDATE_TIME, AUTHOR, ALARM_EMAIL, SCHEDULE_TYPE, SCHEDULE_CONF, MISFIRE_STRATEGY, EXECUTOR_ROUTE_STRATEGY, EXECUTOR_HANDLER, EXECUTOR_PARAM, EXECUTOR_BLOCK_STRATEGY, EXECUTOR_TIMEOUT, EXECUTOR_FAIL_RETRY_COUNT, GLUE_TYPE, GLUE_SOURCE, GLUE_REMARK, GLUE_UPDATETIME, CHILD_JOBID) VALUES (1, 1, '测试任务1', to_date('2018-11-03 22:21:31','yyyy-mm-dd hh24:mi:ss'), to_date('2018-11-03 22:21:31','yyyy-mm-dd hh24:mi:ss'), 'XXL', '', 'CRON', '0 0 0 * * ? *', 'DO_NOTHING', 'FIRST', 'DEMOJOBHANDLER', '', 'SERIAL_EXECUTION', 0, 0, 'BEAN', '', 'GLUE代码初始化', to_date('2018-11-03 22:21:31','yyyy-mm-dd hh24:mi:ss'), '');
INSERT INTO XXL_JOB_USER(ID, USERNAME, PASSWORD, ROLE, PERMISSION) VALUES (1, 'admin', 'e10adc3949ba59abbe56e057f20f883e', 1, NULL);
INSERT INTO XXL_JOB_LOCK ( LOCK_NAME) VALUES ( 'SCHEDULE_LOCK');

COMMIT;