package netplus.serial.api.pojo;

import java.io.Serializable;

/**
 */
public class SerialSq implements Serializable {
    /**
     */
    private Integer id;

    /**
     * 流水号key
     */
    private String serialName;

    /**
     * 序列
     */
    private Integer serialSq;

    /**
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table serial_sq
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 
     *
     * @return id 
     */
    public Integer getId() {
        return id;
    }

    /**
     * 
     *
     * @param id 
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 流水号key
     *
     * @return serial_name 流水号key
     */
    public String getSerialName() {
        return serialName;
    }

    /**
     * 流水号key
     *
     * @param serialName 流水号key
     */
    public void setSerialName(String serialName) {
        this.serialName = serialName == null ? null : serialName.trim();
    }

    /**
     * 序列
     *
     * @return serial_sq 序列
     */
    public Integer getSerialSq() {
        return serialSq;
    }

    /**
     * 序列
     *
     * @param serialSq 序列
     */
    public void setSerialSq(Integer serialSq) {
        this.serialSq = serialSq;
    }

    /**
     * 
     *
     * @return app_id 
     */
    public String getAppId() {
        return appId;
    }

    /**
     * 
     *
     * @param appId 
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }
}