-- add by lixinchen 20220118 :tbmqq406型规字段的长度修改
ALTER TABLE YGMALLUSER.TBMQQ406
    MODIFY (THRPLATSPEC VARCHAR2(200));

-- add by qinyi 20220311 : 订单表增加费用预算部门字段
ALTER TABLE  YGMALLUSER.TBMQQ440
    ADD (
    COSTDEPTPK VARCHAR2(64),
    COSTDEPTNAME VARCHAR2(128),
    COSTDEPTNUM VARCHAR2(64)
    );
COMMENT ON COLUMN YGMALLUSER.TBMQQ440.COSTDEPTPK IS '费用预算部门PK';
COMMENT ON COLUMN YGMALLUSER.TBMQQ440.COSTDEPTNAME IS '费用预算部门名称';
COMMENT ON COLUMN YGMALLUSER.TBMQQ440.COSTDEPTNUM IS '费用预算部门编号';