server:
  port: 20006

---
spring:
  profiles: default
  application:
    name: netplus-provider-web

---
spring:
  profiles: ygmall_test
  application:
    name: netplus-provider-web


---
spring:
  profiles: ygmall_prod
  application:
    name: netplus-provider-web



